### ISSUE TITLE
.ftpignore - how to config?

### ISSUE THREAD

**Issue by gravitymedianet** [matteotonini/multiple-remote-ftp#6]
When using .ftpignore files, should you also follow the same practice?

DEVELOPMENT.ftpignore

And should it be put in the /ftpconfigs folder?

**Comment by matteo-tonini** [comment]
Hi, 

not supported at the moment. 
I will add it soon in the next release.

**Comment by gravitymedianet** [comment]
Thanks

**Comment by matteo-tonini** [comment]
I have added the support for .ftpignore files in the new v1.1.0.
I bumped the version number to a whole unit as I consider this a major release:
It is not backward compatible with the previous one, the /ftpconfigs folder structure changes.
It is very easy to migrate though, just check the README.

**Comment by gravitymedianet** [comment]
Thank you!
